# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2.1

commands:
  build-cmd:
   steps:
      # Get the code
      - checkout
      # Print PHP version
      - run: php -v
      # Update software and install a few things
      - run: sudo apt update
      - run: sudo apt install -y zip unzip gzip tar
      - run: composer require --dev phpunit/phpunit ^9
      # Ensure we always have access to PHP 7.4, PHP 8.0 and PHP 8.1.
      # Different versions are used for PHP linting, PHPCS scanning and SVG scanning.
      # Note: This uses a third-party package, should be safe as no secrets are used during this build.
      - run: sudo add-apt-repository -y ppa:ondrej/php
      - run: sudo apt install -y php7.4 php7.4-dom php7.4-curl php7.4-mbstring 
      - run: sudo apt install -y php8.0 php8.0-dom php8.0-curl php8.0-mbstring
      - run: sudo apt install -y php8.1 php8.1-dom php8.1-curl php8.1-mbstring
      # Install all the tools vip-go-ci needs, remove vip-go-ci itself though
      - run: bash ~/project/tools-init.sh
      - run: rm -rf ~/vip-go-ci-tools/vip-go-ci
      # Change paths to vital tools needed, ensure we use different
      # PHP versions for different types of scanning.
      - run: cat ~/project/unittests.ini.dist | sed 's/\/home\/phpunit\//\/home\/circleci\//' | sed 's/phpcs-php-path=\/usr\/bin\/php/phpcs-php-path=\/usr\/bin\/php7.4/g' | sed 's/svg-php-path=\/usr\/bin\/php/svg-php-path=\/usr\/bin\/php8.1/g'  > ~/project/unittests.ini
      # No secrets available for unit-tests
      - run: touch ~/project/unittests-secrets.ini
      # Prepare phpunit configuration file
      - run: sed 's/PROJECT_DIR/\/home\/circleci\/project/g' ~/project/phpunit.xml.dist > ~/project/phpunit.xml
      # Move to project directory
      - run: cd ~/project
      # Run unit tests
      - run: VIPGOCI_TESTING_DEBUG_MODE=true ./vendor/bin/phpunit --testsuite=unit-tests
      # Run integration tests
      - run: VIPGOCI_TESTING_DEBUG_MODE=true ./vendor/bin/phpunit --testsuite=integration-tests
      # Run PHPCS, check for PHP compatibility issues
      - run: ~/vip-go-ci-tools/phpcs/bin/phpcs --runtime-set 'testVersion' '8.1-'  --standard=PHPCompatibility,PHPCompatibilityParagonieRandomCompat,PHPCompatibilityParagonieSodiumCompat --ignore="vendor/*"  ~/project

# List of images at: https://circleci.com/developer/images/image/cimg/php#image-tags
jobs:
  testphp80:
    docker:
       - image: cimg/php:8.0.15
    steps:
       - build-cmd

  testphp81:
    docker:
      - image: cimg/php:8.1.2
    steps:
      - build-cmd

workflows:
  vipgocitests:
    jobs:
     - testphp80
     - testphp81
