# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.3.9-stretch

      # List of images at: https://circleci.com/docs/2.0/circleci-images/
      # Using the RAM variation mitigates I/O contention
      # for database intensive operations.
      # - image: circleci/mysql:5.7-ram
      #
      # - image: redis:2.8.19

    steps:
      - checkout
      - run: sudo apt update 
      - run: sudo docker-php-ext-install zip
      - run: sudo apt search phpunit
#      - run: sudo apt install -y phpunit
      - run: find .
      - run: phpunit -vv  
