name: CI

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-testing:
    name: Run unit tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.0'
          - '8.1'
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@2.18.1
        with:
          coverage: none
          php-version: ${{ matrix.php }}
          tools: phpunit:9
        env:
          fail-fast: 'true'

      - name: Configure PHPUnit
        run: sed "s:PROJECT_DIR:$(pwd):g" phpunit.xml.dist > phpunit.xml

      - name: Run unit tests
        run: phpunit --testsuite=unit-tests
        env:
          VIPGOCI_TESTING_DEBUG_MODE: 'true'

  integration-testing:
    name: Run integration tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.0'
          - '8.1'
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Instal PHP
        run: |
          set -ex
          sudo apt-get -qq update
          sudo apt-get -qq install eatmydata
          sudo eatmydata add-apt-repository --yes --update ppa:ondrej/php
          sudo eatmydata apt-get -qq install --no-install-recommends php7.4 php7.4-dom php7.4-curl php7.4-mbstring
          sudo eatmydata apt-get -qq install --no-install-recommends php8.0 php8.0-dom php8.0-curl php8.0-mbstring
          sudo eatmydata apt-get -qq install --no-install-recommends php8.1 php8.1-dom php8.1-curl php8.1-mbstring

      - name: Install tools
        run: |
          ./tools-init.sh
          rm -rf ~/vip-go-ci-tools/vip-go-ci

      - name: Configure tools
        run: |
          sed "s:/home/phpunit/:${HOME}/:; s:phpcs-php-path=/usr/bin/php:phpcs-php-path=/usr/bin/php7.4:g; s:svg-php-path=/usr/bin/php:svg-php-path=/usr/bin/php8.1:g" unittests.ini.dist > unittests.ini
          touch unittests-secrets.ini
          sed "s:PROJECT_DIR:$(pwd):g" phpunit.xml.dist > phpunit.xml

      - name: Install composer
        run: |
          sudo wget -q https://getcomposer.org/download/latest-stable/composer.phar -O /usr/local/bin/composer
          sudo chmod a+rx /usr/local/bin/composer

      - name: Set default PHP version
        run: sudo update-alternatives --set php "/usr/bin/php${{ matrix.php }}"

      - name: Install PHPUnit
        run: composer require --dev --no-interaction phpunit/phpunit:^9

      - name: Run unit tests
        run: ./vendor/bin/phpunit --testsuite=integration-tests
        env:
          VIPGOCI_TESTING_DEBUG_MODE: 'true'

  lint:
    name: PHPCS check
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@2.18.1
        with:
          coverage: none
          php-version: 8.1

      - name: Install tools
        run: |
          ./tools-init.sh
          rm -rf ~/vip-go-ci-tools/vip-go-ci

      - name: Run PHPCS
        run: |
          ~/vip-go-ci-tools/phpcs/bin/phpcs --runtime-set 'testVersion' '8.1-'  --standard=PHPCompatibility,PHPCompatibilityParagonieRandomCompat,PHPCompatibilityParagonieSodiumCompat --ignore="vendor/*" .
