name: CI

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  unit-testing:
    name: Run unit tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.0'
          - '8.1'
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@2.18.1
        with:
          coverage: none
          php-version: "${{ matrix.php }}"
          tools: phpunit:9
        env:
          fail-fast: 'true'

      - name: Configure PHPUnit
        run: sed "s:PROJECT_DIR:$(pwd):g" phpunit.xml.dist > phpunit.xml

      - name: Run unit tests
        run: phpunit --testsuite=unit-tests
        env:
          VIPGOCI_TESTING_DEBUG_MODE: 'true'

  integration-testing:
    name: Run integration tests (PHP ${{ matrix.php }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - '8.0'
          - '8.1'
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Set up PHP 7.4
        uses: shivammathur/setup-php@2.18.1
        with:
          coverage: none
          php-version: "7.4"

      - name: Set up PHP 8.0
        uses: shivammathur/setup-php@2.18.1
        with:
          coverage: none
          php-version: "8.0"

      - name: Set up PHP 8.1
        uses: shivammathur/setup-php@2.18.1
        with:
          coverage: none
          php-version: "8.1"
          tools: phpunit:9
        env:
          fail-fast: 'true'

      - name: Install tools
        run: |
          ./tools-init.sh
          rm -rf ~/vip-go-ci-tools/vip-go-ci

      - name: Configure tools
        run: |
          sed "s:/home/phpunit/:${HOME}/:; s:phpcs-php-path=/usr/bin/php:phpcs-php-path=/usr/bin/php7.4:g; s:svg-php-path=/usr/bin/php:svg-php-path=/usr/bin/php8.1:g" unittests.ini.dist > unittests.ini
          touch unittests-secrets.ini
          sed "s:PROJECT_DIR:$(pwd):g" phpunit.xml.dist > phpunit.xml

      - name: Set default PHP version
        run: sudo update-alternatives --set php "/usr/bin/php${{ matrix.php }}"

      - name: Run integration tests
        run: phpunit --testsuite=integration-tests
        env:
          VIPGOCI_TESTING_DEBUG_MODE: 'true'

  phpcs-scan:
    name: PHPCS scan
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@2.18.1
        with:
          coverage: none
          php-version: 8.1

      - name: Install tools
        run: |
          ./tools-init.sh
          rm -rf ~/vip-go-ci-tools/vip-go-ci

      - name: Run PHPCS
        run: |
          ~/vip-go-ci-tools/phpcs/bin/phpcs --runtime-set 'testVersion' '8.1-'  --standard=PHPCompatibility,PHPCompatibilityParagonieRandomCompat,PHPCompatibilityParagonieSodiumCompat --ignore="vendor/*" .
